[relabel]
allow-unauthenticated = [
    "A-*",
    "C-*",
    "D-*",
    "E-*",
    "F-*",
    "I-*",
    "NLL-*",
    "O-*",
    "S-*",
    "T-*",
    "WG-*",
    "needs-fcp",
    "relnotes",
    "requires-nightly",
    "regression-*",
    "perf-*",
    "AsyncAwait-OnDeck",
    "initial-comment-period",
]

# [major-change]
# second_label = "initial-comment-period"
# meeting_label = "I-nominated"
# # can be found by looking for the first number in URLs, e.g. https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler
# zulip_stream = 327149
# zulip_ping = "T-libs-api"
